// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientRegistrationService.proto

package ie.nci.PatientRegistrationService;

public final class PatientRegistrationServiceImpl {
  private PatientRegistrationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientRegistrationService_Patient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientRegistrationService_Patient_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientRegistrationService_PatientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientRegistrationService_PatientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientRegistrationService_PatientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientRegistrationService_PatientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n PatientRegistrationService.proto\022\032Pati" +
      "entRegistrationService\"B\n\007Patient\022\013\n\003pps" +
      "\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\017\n\007add" +
      "ress\030\004 \001(\t\"F\n\016PatientRequest\0224\n\007patient\030" +
      "\001 \001(\0132#.PatientRegistrationService.Patie" +
      "nt\"G\n\017PatientResponse\0224\n\007patient\030\001 \001(\0132#" +
      ".PatientRegistrationService.Patient2\201\001\n\032" +
      "PatientRegistrationService\022c\n\010register\022*" +
      ".PatientRegistrationService.PatientReque" +
      "st\032+.PatientRegistrationService.PatientR" +
      "esponseBE\n!ie.nci.PatientRegistrationSer" +
      "viceB\036PatientRegistrationServiceImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PatientRegistrationService_Patient_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PatientRegistrationService_Patient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientRegistrationService_Patient_descriptor,
        new java.lang.String[] { "Pps", "Name", "Age", "Address", });
    internal_static_PatientRegistrationService_PatientRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PatientRegistrationService_PatientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientRegistrationService_PatientRequest_descriptor,
        new java.lang.String[] { "Patient", });
    internal_static_PatientRegistrationService_PatientResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PatientRegistrationService_PatientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientRegistrationService_PatientResponse_descriptor,
        new java.lang.String[] { "Patient", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
