// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientRegistrationService.proto

package ie.nci.PatientRegistrationService;

public interface PatientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientRegistrationService.Patient)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pps = 1;</code>
   */
  java.lang.String getPps();
  /**
   * <code>string pps = 1;</code>
   */
  com.google.protobuf.ByteString
      getPpsBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();

  /**
   * <code>string address = 4;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
