// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientRegistrationService.proto

package ie.nci.PatientRegistrationService;

public interface PatientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientRegistrationService.PatientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.PatientRegistrationService.Patient patient = 1;</code>
   */
  boolean hasPatient();
  /**
   * <code>.PatientRegistrationService.Patient patient = 1;</code>
   */
  ie.nci.PatientRegistrationService.Patient getPatient();
  /**
   * <code>.PatientRegistrationService.Patient patient = 1;</code>
   */
  ie.nci.PatientRegistrationService.PatientOrBuilder getPatientOrBuilder();
}
